### ISSUE TITLE
Questions reagarding Transaction.sol

### ISSUE THREAD

**Issue by SushantBabu97** [sangya2001/TransacIT#3]
I think you have issues with the contract, Transaction.sol.  (Possibility: I might have misunderstood it)

a) Why does every account have their own fund? Are not they supposed to have their fund deposited as a collective fund?

b) When an account sends its fund, why does not the fund amount in check amount decrease? Is the fund being sent to other accounts independent of the deposited fund? If it's independent, why should the fund amount be sent should have least than the deposited fund amount??

c) The fund received by an account more than one time and from multiple sources doesn't add but replaces the previously received.

**Comment by SushantBabu97** [comment]
> I think you have issues with the contract, Transaction.sol. (Possibility: I might have misunderstood it)
> 
> a) Why does every account have their own fund? Are not they supposed to have their fund deposited as a collective fund?
> 
> b) When an account sends its fund, why does not the fund amount in check amount decrease? Is the fund being sent to other accounts independent of the deposited fund? If it's independent, why should the fund amount be sent should have least than the deposited fund amount??
> 
> c) The fund received by an account more than one time and from multiple sources doesn't add but replaces the previously received.

**Comment by sangya2001** [comment]
> I think you have issues with the contract, Transaction.sol. (Possibility: I might have misunderstood it)
> 
> a) Why does every account have their own fund? Are not they supposed to have their fund deposited as a collective fund?
> 
> b) When an account sends its fund, why does not the fund amount in check amount decrease? Is the fund being sent to other accounts independent of the deposited fund? If it's independent, why should the fund amount be sent should have least than the deposited fund amount??
> 
> c) The fund received by an account more than one time and from multiple sources doesn't add but replaces the previously received.

a. There are lots of accounts so there is absent of collective fund and every account as their own fund.
b. Sending fund means I am sending so my amount decreases from the total amount.
